# NOTE: Only Windows Server 2012 supported at this time
#os: Windows Server 2012
#os: Windows 8.1
os: Unstable

# NOTE: That platform relates to msbuild NOT the host OS platform
platform:
    - Win32    
configuration:
    - Release

# Use build cache for Cygwin installation
#cache:
#    C:\cygwin

# Use shallow clone for speed as we only need the last commit to build     
#shallow_clone: true
#clone_depth: 1

environment:
    global:
        CYG_ROOT: C:/cygwin
        MONO_INSTALL_FOLDER_WIN: C:\monoinstall
        MONO_INSTALL_FOLDER_CYG: /cygdrive/c/monoinstall
        NSIS_ROOT: C:\nsis

# Only build specific branches as master is unlikely to build
#branches:
#    only:
#      - mono-3.10.0-branch

init:
    - 'echo Appveyor Test'
    - 'echo System architecture: %PLATFORM%'
    - 'echo %APPVEYOR_REPO_NAME%'

install:
    - 'echo Retrieving NSIS'
    - 'appveyor DownloadFile "http://sunet.dl.sourceforge.net/project/nsis/NSIS 2/2.46/nsis-2.46-setup.exe" -FileName nsissetup.exe'
    - 'echo Setting up NSIS'
    - 'nsissetup.exe /S /D=%NSIS_ROOT%'
    - 'echo Done setting up NSIS'
    - 'appveyor DownloadFile http://www.dynamicdevices.co.uk/downloads/Mono-3.10.0.zip -FileName c:\mono-binaries.zip'
    - '7z ef c:\mono-binaries.zip'
    - 'ren c:\Mono-3.10.0 c:\monoinstall'

build_script:
    - 'echo OK'
    - '%NSIS_ROOT%\makensis /DMILESTONE=3.10.0 /DSOURCE_INSTALL_DIR=C:\monoinstall\*.* /DBUILDNUM=1.0.4 monowiz.win32.nsi'

