# NOTE: Only Windows Server 2012 supported at this time
#os: Windows Server 2012
#os: Windows 8.1
os: Unstable

# NOTE: That platform relates to msbuild NOT the host OS platform
platform:
    - Win32    
configuration:
    - Release

# Use build cache for Cygwin installation
#cache:
#    C:\cygwin

# Use shallow clone for speed as we only need the last commit to build     
#shallow_clone: true
#clone_depth: 1

environment:
    global:
        CYG_ROOT: C:/cygwin
#        CYG_MIRROR: http://cygwin.mirror.constant.com
        CYG_MIRROR: ftp://mirrors.kernel.org/sourceware/cygwin
        CYG_CACHE: C:/cygwin/var/cache/setup
#        MONO_INSTALL_FOLDER: C:\\monoinstall
        MONO_INSTALL_FOLDER_WIN: C:\monoinstall
        MONO_INSTALL_FOLDER_CYG: /cygdrive/c/monoinstall
        NSIS_INSTALL_FOLDER: C:\nsis

#    matrix:
#        - 
#            CYG_ARCH: x86

# Only build specific branches as master is unlikely to build
branches:
    only:
      - mono-3.10.0-branch

init:
    - 'echo Appveyor Test'
    - 'echo System architecture: %PLATFORM%'
    - 'echo %APPVEYOR_REPO_NAME%'
    - 'cd %APPVEYOR_BUILD_FOLDER%'

install:
    - 'cd c:\'
    - 'appveyor DownloadFile http://www.dynamicdevices.co.uk/Mono-3.10.0.zip -FileName mono-binaries.zip'
    - '7z e mono-binaries.zip'
    - 'dir'

build_script:
    - 'echo OK'

